### ISSUE TITLE
Switching between two mapbox maps.

### ISSUE THREAD

**Issue by SeanBannister** [dayjournal/mapbox-gl-opacity#1]
Thank you for this plugin. I've been trying to figure out how I can specify multiple mapbox vector maps in the `baseLayers`. I'm trying to allow the user to switch between:
mapbox://styles/mapbox/streets-v11
and
mapbox://styles/mapbox/light-v10

Generally this would be done with `map.setStyle` seen [here](https://docs.mapbox.com/mapbox-gl-js/example/setstyle/). But wondering if it's possible with `map.addLayer`.

**Comment by dayjournal** [comment]
Hi,
baseLayers is for raster tiles. You may need to modify the plugin to apply the mapbox style.
I'll consider it.

**Comment by SeanBannister** [comment]
Cheers, I ended up using the raster layer versions of the maps but this would be an awesome feature to still be able to use vector.
